[package]
name = "ethane-test"
version = "0.1.0"
authors = ["hajnalandor <andor.hajnal@fluidpay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethane = "0.1.0"
tiny-keccak = "2"